---
---

```{r include=F}
source(here::here("code/setup.R"))
# Load sources, articles, journos
datadir <- "data/masterdata2"
```

```{r}
all.articles <- read_tsv(here(datadir, "articles.tsv"))
all.sources <- read_tsv(here(datadir, "sources.tsv"))
sources <- all.sources %>%
    filter(policy_label_gpt) %>%
    mutate(
        lean = case_when(
            pol_party == "Democrat" ~ "left",
            pol_party == "Republican" ~ "right",
            category.slant == "Environmental" ~ "left",
            category.slant == "Fossil Fuel" ~ "right",
            cfscore.impute < 0.25 ~ "left",
            cfscore.impute > 0.25 ~ "right",
            TRUE ~ "center"
        ),
        lean_src = case_when(
            pol_party == "Democrat" ~ "pol",
            pol_party == "Republican" ~ "pol",
            category.slant == "Environmental" ~ "cat",
            category.slant == "Fossil Fuel" ~ "cat",
            cfscore.impute < 0.25 ~ "dime",
            cfscore.impute > 0.25 ~ "dime",
            TRUE ~ "none"
        )
    )

sources %>%
    group_by(entity_id, category.slant, lean, lean_src) %>%
    summarize(
        entity_name = first(entity_name),
        entity_desc = first(entity_desc),
        cfscore.i2 = fmode(cfscore.i2),
        n = n()
    ) %>%
    arrange(desc(n)) %>%
    select(!c(entity_id)) %>%
    head(100) %>%
    kable()
```

# Randomly pick some sources
```{r}
set.seed(10)
sources %>%
    sample_n(100) %>%
    group_by(entity_id, category.slant, lean, lean_src) %>%
    summarize(
        entity_name = first(entity_name),
        entity_desc = first(entity_desc),
        cfscore.i2 = fmode(cfscore.i2),
        n = n()
    ) %>%
    arrange(desc(n)) %>%
    select(!c(entity_id)) %>%
    kable()
```
```
